### ISSUE TITLE
Numeric graph shows nulls

### ISSUE THREAD

**Issue by YonatanNitzan** [Spikes-2212-Programming-Guild/mercury-server#8]

**Comment by YonatanNitzan** [comment]
Seems there isn't a problem in the code, just some preexisting null data that was in the collection.
Deleted all collections and entered new data - no nulls.

**Comment by itamargreen** [comment]
@YonatanNitzan So is the problem gone? do you know why was there preexisting null data?

**Comment by TheArchNemesis** [comment]
The problem probably existed because a question was added after some data already was stored in the collection

**Comment by itamargreen** [comment]
@TheArchNemesis Yep. I can repro that.

btw, It might be useful to put an `example.json` file in the repo (i.e. allow git to track a specific game `.json` so that it's always clear what the format is supposed to be)
